In [199]:
import pandas as pd 
import numpy as np

In [200]:
df = pd.read_csv("/home/fwzblk/Projects/prime2/pytorch-prime/p3/my_code/ann-classification/DateFruit_Dataset.csv")

In [201]:
df.head(10)

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.9080,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.1440,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.3940,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.2100,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.3540,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI
5,408953,2326.6931,840.1821,622.0076,0.6722,721.5921,0.9974,410036,0.7805,1.3508,...,3.6309,6.0285,6.2159,-41140371456,-33146710016,-27907301376,49.7001,45.3190,39.7371,BERHI
6,451414,2457.2080,889.3253,652.4316,0.6796,758.1281,0.9970,452755,0.7877,1.3631,...,3.0703,3.4163,4.9168,-63711666176,-64060743680,-52603465728,57.8060,58.5449,52.4199,BERHI
7,382636,2275.7791,808.0833,609.2819,0.6569,697.9880,0.9931,385277,0.7032,1.3263,...,3.6756,7.0258,5.3254,-29873577984,-33570080768,-33054025728,45.1768,48.2407,47.2167,BERHI
8,546063,2714.9480,916.3737,766.4536,0.5481,833.8279,0.9882,552598,0.7710,1.1956,...,3.4640,3.7416,4.8120,-95262416896,-79321833472,-69569445888,64.6188,59.9127,55.6509,BERHI
9,420044,2391.1230,836.9280,645.1822,0.6370,731.3116,0.9918,423531,0.7853,1.2972,...,3.3729,4.2898,5.4637,-74341122048,-58172182528,-42640556032,64.9094,58.2771,48.4820,BERHI

In [202]:
df.shape

(898, 35)

In [203]:
df["Class"].unique()

<StringArray>
['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY']
Length: 7, dtype: str

In [204]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [205]:
classes = df["Class"]
classes.value_counts()

Class
DOKOL     204
SAFAVI    199
ROTANA    166
DEGLET     98
SOGAY      94
IRAQI      72
BERHI      65
Name: count, dtype: int64

In [206]:
x = df.drop(labels="Class",axis=1)
x

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.9080,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.1440,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.3940,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.2100,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.3540,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,255403,1925.3650,691.8453,477.1796,0.7241,570.2536,0.9785,261028,0.7269,1.4499,...,-0.1398,2.2423,2.3704,2.7202,-25296416768,-19168882688,-18473392128,49.0869,43.0422,42.4153
894,365924,2664.8230,855.4633,551.5447,0.7644,682.5752,0.9466,386566,0.6695,1.5510,...,0.5611,3.4109,3.5805,3.9910,-31605219328,-21945366528,-19277905920,46.8086,39.1046,36.5502
895,254330,1926.7360,747.4943,435.6219,0.8126,569.0545,0.9925,256255,0.7240,1.7159,...,0.2665,2.2759,2.5090,2.6951,-22242772992,-19594921984,-17592152064,44.1325,40.7986,40.9769
896,238955,1906.2679,716.6485,441.8297,0.7873,551.5859,0.9604,248795,0.6954,1.6220,...,0.5325,2.6769,2.6874,2.7991,-26048595968,-21299822592,-19809978368,51.2267,45.7162,45.6260
897,343792,2289.2720,823.8438,534.7757,0.7607,661.6113,0.9781,351472,0.6941,1.5405,...,0.4318,2.5138,3.0369,3.0865,-31983476736,-20482514944,-21219354624,47.3454,38.6966,39.6738

In [207]:
y = df['Class']
y

0      BERHI
1      BERHI
2      BERHI
3      BERHI
4      BERHI
       ...
893    SOGAY
894    SOGAY
895    SOGAY
896    SOGAY
897    SOGAY
Name: Class, Length: 898, dtype: str

In [208]:
x.shape

(898, 34)

In [209]:
y.shape

(898,)

In [210]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

y_encoded = le.fit_transform(y)

In [211]:
y_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [212]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

x_train, x_val, y_train, y_val = train_test_split(
    x_train, y_train,
    test_size=0.15,
    random_state=42,
    stratify=y_train
)

In [213]:
x_train.shape

(610, 34)

In [214]:
x_test.shape

(180, 34)

In [215]:
y_train.shape

(610,)

In [216]:
y_test.shape

(180,)

In [217]:
pd.Series(le.inverse_transform(y_train)).value_counts()

DOKOL     139
SAFAVI    135
ROTANA    113
DEGLET     66
SOGAY      64
IRAQI      49
BERHI      44
Name: count, dtype: int64

In [218]:
pd.Series(le.inverse_transform(y_test)).value_counts()

DOKOL     41
SAFAVI    40
ROTANA    33
DEGLET    20
SOGAY     19
IRAQI     14
BERHI     13
Name: count, dtype: int64

In [219]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_val_scaled = scaler.transform(x_val)
x_test_scaled = scaler.transform(x_test)

In [220]:
import torch
import torch.nn as nn

x_train_tensor = torch.tensor(x_train_scaled, dtype=torch.float32)
x_val_tensor = torch.tensor(x_val_scaled, dtype=torch.float32)
x_test_tensor = torch.tensor(x_test_scaled, dtype=torch.float32)

y_train_tensor = torch.tensor(y_train, dtype=torch.long)
y_val_tensor = torch.tensor(y_val, dtype=torch.long)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [221]:
x_train_tensor.shape

torch.Size([610, 34])

In [222]:
x_train_tensor.dtype

torch.float32

In [223]:
x_test_tensor.shape

torch.Size([180, 34])

In [224]:
x_test_tensor.dtype

torch.float32

In [225]:
y_train_tensor.shape

torch.Size([610])

In [226]:
y_test_tensor.shape

torch.Size([180])

In [227]:
y_train_tensor.dtype

torch.int64

In [228]:
y_test_tensor.dtype

torch.int64

In [229]:
from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(x_train_tensor, y_train_tensor)
val_dataset = TensorDataset(x_val_tensor, y_val_tensor)
test_dataset = TensorDataset(x_test_tensor, y_test_tensor)

In [230]:
train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False
)

In [231]:
class ANN(nn.Module):
    def __init__(self):
        super(ANN, self).__init__()

        self.model = nn.Sequential(
            # first hidden layer
            nn.Linear(x_train.shape[1], 64),
            nn.ReLU(),

            # second hidden layer
            nn.Linear(64, 32),
            nn.ReLU(),

            # output layer
            nn.Linear(32,7)
        )

    def forward(self, x):
        return self.model(x)

In [232]:
model = ANN()

In [233]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001) # learning rate by default is 0.001

In [234]:
epochs = 100 
train_losses=[]
val_losses=[]
best_val_loss=float("inf")
for epoch in range(epochs):
    model.train()
    running_loss = 0

    #training 
    for xb,yb in train_loader:
        optimizer.zero_grad()
        output = model(xb)
        loss = criterion(output,yb)
        loss.backward()
        optimizer.step()
        running_loss += float(loss)

    epoch_train_loss = running_loss/len(train_loader)
    train_losses.append(epoch_train_loss)

    #validation 

    model.eval()
    running_val_loss=0

    for xv,yv in val_loader:
        with torch.no_grad():
            v_output = model(xv)
            v_loss = criterion(v_output,yv)
            running_val_loss+= float(v_loss)
    epoch_val_loss = running_val_loss/len(val_loader)
    val_losses.append(epoch_val_loss)

    print(f"epoch{epoch+1} | training loss = {epoch_train_loss} & validation loss = {epoch_val_loss} ")
    if epoch_val_loss < best_val_loss:
        best_val_loss= epoch_val_loss
        torch.save(model.state_dict(),"best-model2.pt")

epoch1 | training loss = 1.7580156207084656 & validation loss = 1.5391343235969543
epoch2 | training loss = 1.3140783220529557 & validation loss = 1.1170235127210617
epoch3 | training loss = 0.9449126362800598 & validation loss = 0.898097351193428
epoch4 | training loss = 0.8416924178600311 & validation loss = 0.7383556514978409
epoch5 | training loss = 0.6388897441327572 & validation loss = 0.6285276114940643
epoch6 | training loss = 0.546852957829833 & validation loss = 0.5367090553045273
epoch7 | training loss = 0.5023190081119537 & validation loss = 0.47855789214372635
epoch8 | training loss = 0.44108508080244063 & validation loss = 0.4318185970187187
epoch9 | training loss = 0.3951151091605425 & validation loss = 0.38247187435626984
epoch10 | training loss = 0.3978738054633141 & validation loss = 0.34992460906505585
epoch11 | training loss = 0.3618528589606285 & validation loss = 0.3114035651087761
epoch12 | training loss = 0.3149842582643032 & validation loss = 0.288039468228817
epoch13 | training loss = 0.2876920941285789 & validation loss = 0.2699638158082962
epoch14 | training loss = 0.28701944202184676 & validation loss = 0.263079397380352
epoch15 | training loss = 0.29669082164764404 & validation loss = 0.24961747229099274
epoch16 | training loss = 0.3030085518956184 & validation loss = 0.23497670143842697
epoch17 | training loss = 0.2517110385000706 & validation loss = 0.25356514006853104
epoch18 | training loss = 0.22262782752513885 & validation loss = 0.21708529442548752
epoch19 | training loss = 0.22274165973067284 & validation loss = 0.21515199169516563
epoch20 | training loss = 0.21175612173974515 & validation loss = 0.20239145308732986
epoch21 | training loss = 0.20217408873140813 & validation loss = 0.19983123987913132
epoch22 | training loss = 0.20298349261283874 & validation loss = 0.20074867643415928
epoch23 | training loss = 0.20010608360171317 & validation loss = 0.1950161550194025
epoch24 | training loss = 0.18245242014527321 & validation loss = 0.19072827696800232
epoch25 | training loss = 0.17981051467359066 & validation loss = 0.18974414095282555
epoch26 | training loss = 0.17402019686996936 & validation loss = 0.18199964426457882
epoch27 | training loss = 0.17230942584574221 & validation loss = 0.18930753879249096
epoch28 | training loss = 0.1623010154813528 & validation loss = 0.18041895981878042
epoch29 | training loss = 0.16314613670110703 & validation loss = 0.18193156085908413
epoch30 | training loss = 0.1558397561001584 & validation loss = 0.1881120866164565
epoch31 | training loss = 0.15014025749442225 & validation loss = 0.17357895243912935
epoch32 | training loss = 0.16666500493884087 & validation loss = 0.1867491314187646
epoch33 | training loss = 0.14985719174146653 & validation loss = 0.1628532288596034
epoch34 | training loss = 0.1664417989552021 & validation loss = 0.1703460467979312
epoch35 | training loss = 0.14688308336735645 & validation loss = 0.17335817962884903
epoch36 | training loss = 0.14470068868249655 & validation loss = 0.1771484762430191
epoch37 | training loss = 0.1383690321817994 & validation loss = 0.17179648764431477
epoch38 | training loss = 0.13250096046540422 & validation loss = 0.17263189516961575
epoch39 | training loss = 0.13031025119125844 & validation loss = 0.18055826239287853
epoch40 | training loss = 0.12893833424896 & validation loss = 0.17338479310274124
epoch41 | training loss = 0.12629305850714445 & validation loss = 0.1687403004616499
epoch42 | training loss = 0.12093321566935629 & validation loss = 0.17228063009679317
epoch43 | training loss = 0.13394954819232224 & validation loss = 0.1705173160880804
epoch44 | training loss = 0.13455431433394552 & validation loss = 0.17643194878473878
epoch45 | training loss = 0.11710781191213755 & validation loss = 0.17430971981957555
epoch46 | training loss = 0.11986444313079118 & validation loss = 0.17690850049257278
epoch47 | training loss = 0.11265578710008413 & validation loss = 0.1787806018255651
epoch48 | training loss = 0.12423344096168876 & validation loss = 0.1708591291680932
epoch49 | training loss = 0.10878609520791542 & validation loss = 0.19058541813865304
epoch50 | training loss = 0.12700358908623458 & validation loss = 0.17553441878408194
epoch51 | training loss = 0.1250429166480899 & validation loss = 0.19150312803685665
epoch52 | training loss = 0.1034759044763632 & validation loss = 0.17854424566030502
epoch53 | training loss = 0.10314979664981365 & validation loss = 0.17433786392211914
epoch54 | training loss = 0.11127682328224182 & validation loss = 0.17302355356514454
epoch55 | training loss = 0.1002020699903369 & validation loss = 0.17412739153951406
epoch56 | training loss = 0.09876939356327057 & validation loss = 0.1736762896180153
epoch57 | training loss = 0.13488580994307994 & validation loss = 0.18291320651769638
epoch58 | training loss = 0.09679152220487594 & validation loss = 0.19803362153470516
epoch59 | training loss = 0.09319086074829101 & validation loss = 0.18109833914786577
epoch60 | training loss = 0.09183651590719819 & validation loss = 0.17790113668888807
epoch61 | training loss = 0.09099372803902953 & validation loss = 0.17291087843477726
epoch62 | training loss = 0.08954983614385129 & validation loss = 0.17603603564202785
epoch63 | training loss = 0.0827573400689289 & validation loss = 0.1697665387764573
epoch64 | training loss = 0.08287746339992737 & validation loss = 0.17894860124215484
epoch65 | training loss = 0.11531442105770111 & validation loss = 0.19507982674986124
epoch66 | training loss = 0.14063235971261748 & validation loss = 0.14848440885543823
epoch67 | training loss = 0.12601373586803674 & validation loss = 0.19580403994768858
epoch68 | training loss = 0.13902575343381612 & validation loss = 0.20545700518414378
epoch69 | training loss = 0.07979710590443574 & validation loss = 0.19817849714308977
epoch70 | training loss = 0.07594125243194867 & validation loss = 0.18691943027079105
epoch71 | training loss = 0.0727353454567492 & validation loss = 0.18406715244054794
epoch72 | training loss = 0.07098292815499008 & validation loss = 0.18098191358149052
epoch73 | training loss = 0.07820271321106702 & validation loss = 0.17745348066091537
epoch74 | training loss = 0.08063521087169648 & validation loss = 0.1849388526752591
epoch75 | training loss = 0.09790487247519195 & validation loss = 0.1815648595802486
epoch76 | training loss = 0.07367771273638937 & validation loss = 0.1909645963460207
epoch77 | training loss = 0.06951999223383609 & validation loss = 0.17270405031740665
epoch78 | training loss = 0.06616711652604863 & validation loss = 0.18865566328167915
epoch79 | training loss = 0.06729450752027333 & validation loss = 0.17724199034273624
epoch80 | training loss = 0.0706143326126039 & validation loss = 0.18224218674004078
epoch81 | training loss = 0.0669805446988903 & validation loss = 0.17197843175381422
epoch82 | training loss = 0.12280109589919448 & validation loss = 0.18711483757942915
epoch83 | training loss = 0.07916375566273928 & validation loss = 0.18699758034199476
epoch84 | training loss = 0.0795359855517745 & validation loss = 0.18276686314493418
epoch85 | training loss = 0.07602977240458131 & validation loss = 0.16140326391905546
epoch86 | training loss = 0.06892659608274698 & validation loss = 0.17160600516945124
epoch87 | training loss = 0.06023477874696255 & validation loss = 0.1786791356280446
epoch88 | training loss = 0.06263699093833566 & validation loss = 0.1767332861199975
epoch89 | training loss = 0.06430788962170482 & validation loss = 0.17670291848480701
epoch90 | training loss = 0.05693563664572139 & validation loss = 0.1856961203739047
epoch91 | training loss = 0.06121354061178863 & validation loss = 0.1835110392421484
epoch92 | training loss = 0.05547843514068518 & validation loss = 0.1761393053457141
epoch93 | training loss = 0.05352955327834934 & validation loss = 0.18800950422883034
epoch94 | training loss = 0.050304020708426836 & validation loss = 0.196986747905612
epoch95 | training loss = 0.04887408539652753 & validation loss = 0.18793359398841858
epoch96 | training loss = 0.048072478501123325 & validation loss = 0.19114419352263212
epoch97 | training loss = 0.050716355349868535 & validation loss = 0.20048453100025654
epoch98 | training loss = 0.048774006147868934 & validation loss = 0.19509463384747505
epoch99 | training loss = 0.046514632127946244 & validation loss = 0.19786524213850498
epoch100 | training loss = 0.04593658745288849 & validation loss = 0.1986177209764719

In [235]:
model.load_state_dict(torch.load("best-model2.pt", weights_only=True))

In [239]:
model.eval()
test_loss = []
running_test_loss = 0
correct=0
total=0
for xt,yt in test_loader:

    with torch.no_grad():
        t_output = model(xt)
        t_loss = criterion(t_output,yt)
        running_test_loss+=float(t_loss)
        predicted = t_output.argmax(dim=1)
        correct += (predicted == yt).sum().item()
        total+=yt.numel()


epoch_test_loss = running_test_loss/len(test_loader)
test_loss.append(epoch_test_loss)

print(test_loss)

accuracy = (correct/total)*100
print(accuracy)

[0.26483700300256413]
92.77777777777779