In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("globalAirQuality.csv")
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [3]:
df['city'].unique()

<StringArray>
[        'New York',      'Los Angeles',           'London',
            'Paris',           'Berlin',           'Madrid',
             'Rome',          'Toronto',      'Mexico City',
        'São Paulo',     'Buenos Aires',        'Cape Town',
            'Cairo',          'Nairobi',            'Lagos',
            'Dubai',           'Riyadh',             'Doha',
           'Mumbai',            'Delhi',        'Bengaluru',
          'Kolkata',          'Chennai',            'Tokyo',
            'Osaka',            'Seoul',          'Beijing',
         'Shanghai',        'Hong Kong',        'Singapore',
          'Bangkok',     'Kuala Lumpur',          'Jakarta',
           'Sydney',        'Melbourne',         'Auckland',
           'Moscow',         'Istanbul',           'Tehran',
          'Karachi',           'Manila', 'Ho Chi Minh City',
    'San Francisco',          'Chicago',          'Houston',
        'Vancouver',           'Warsaw',        'Stockholm',
         'Helsinki',           'Zurich']
Length: 50, dtype: str

In [4]:
df[['city', 'aqi']]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [5]:
df.loc[9]

timestamp      2025-11-05 03:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               16.464
pm10                               76.631
no2                                28.119
so2                                 8.561
o3                                 79.467
co                                  1.081
aqi                                    76
temperature                         11.49
humidity                           29.403
wind_speed                          3.762
Name: 9, dtype: object

In [14]:
# filtering data 

df[df['aqi'] > 100]
df[(df['aqi'] > 100) & (df['temperature'] > 30)]

df[df['aqi']>100][['city','country']]#chaining 

aqi_value = 100 
df.query("aqi > 100")
df.query("aqi > 100 & temperature > 30 ")[['city', 'aqi']] #chaining with query 
df.query("aqi> @aqi_value & temperature > 30 ")[['city', 'aqi']]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]